version: '3.8'

services:
  web:
    build: .
    image: my_flask_with_sqlite
    ports:
      - "5005:5005"
    environment:
      FLASK_RUN_PORT: 5005
    networks:
      - flask_network

networks:
  flask_network:
    driver: bridge
